version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: react-notes-23
    path: ""
    text-resources:
      - path: src/i18n/*.json
        format: flat-key-value
