version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: testt
    path: ""
    text-resources:
      - path: src/i18n/*.ts
        format: react-hardcoded
