version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: react-notes-22222
    path: ""
    text-resources:
      - path: "*.tsx"
        format: react-hardcoded
