export enum UiActions {
  OPEN_NOTE_DIALOG = 'OPEN_NOTE_DIALOG',
  CLOSE_NOTE_DIALOG = 'CLOSE_NOTE_DIALOG',
  OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG',
  CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG',
}

export enum NoteActions {
  ADD_NOTE = 'ADD_NOTE',
  ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS',
  ADD_NOTE_FAILED = 'ADD_NOTE_FAILED',
}