export type ActionTypes = UiActions | NoteActions | CategoryActions;

export enum UiActions {
  OPEN_NOTE_DIALOG = 'OPEN_NOTE_DIALOG',
  CLOSE_NOTE_DIALOG = 'CLOSE_NOTE_DIALOG',
  OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG',
  CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG',
}

export enum NoteActions {
  CREATE_NOTE = 'CREATE_NOTE',
  CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS',
  CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL',
}

export enum CategoryActions {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL',
  ADD_CATEGORY = 'ADD_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL',
  SELECT_CATEGORY = 'SELECT_CATEGORY',
}