export interface Shortcuts {
  general: Record<string, string>;
  miscellaneous: Record<string, string>;
}

const SHORTCUTS: Shortcuts = {
  general: {
    N: 'SHORTCUTS_DIALOG.OPEN_ADD_NEW_NOTE_DIALOG',
    C: 'SHORTCUTS_DIALOG.CREATE_NEW_CATEGORY',
    E: 'SHORTCUTS_DIALOG.EDIT_NOTE',
    O: 'SHORTCUTS_DIALOG.OPEN_CURRENTLY_SELECTED_NOTE',
    'D, Delete, Backspace': 'SHORTCUTS_DIALOG.DELETE_SELECTED_NOTE_OR_NOTES',
    A: 'SHORTCUTS_DIALOG.ARCHIVE_OR_RESTORE_SELECTED_NOTE_OR_NOTES',
    S: 'SHORTCUTS_DIALOG.OPEN_SETTINGS',
    Escape: 'SHORTCUTS_DIALOG.CLOSE_MOST_RECENT_DIALOG_OR_SETTINGS',
    Enter: 'SHORTCUTS_DIALOG.CONFIRM_ACTION',
    '0-9': 'SHORTCUTS_DIALOG.CATEGORY_QUICK_SELECT',
    '/': 'SHORTCUTS_DIALOG.OPEN_SHORTCUTS_DIALOG',
  },
  miscellaneous: {
    'SHORTCUTS_DIALOG.NOTE_SHIFT_CLICK': 'SHORTCUTS_DIALOG.TOGGLE_MULTISELECT_WHEN_HOLD',
    'SHORTCUTS_DIALOG.NOTE_DOUBLE_CLICK': 'SHORTCUTS_DIALOG.OPEN_CLICKED_NOTE',
    'SHORTCUTS_DIALOG.APP_DOUBLE_CLICK': 'SHORTCUTS_DIALOG.CLEAR_SELECTION_AND_TURN_SINGLE_SELECT',
    'SHORTCUTS_DIALOG.NOTE_RIGHT_CLICK': 'SHORTCUTS_DIALOG.OPEN_NOTE_CONTEXT_MENU',
    'SHORTCUTS_DIALOG.SIDEBAR_CLICK': 'SHORTCUTS_DIALOG.PERSIST_OPENED_SIDEBAR',
    'SHORTCUTS_DIALOG.APP_CLICK_AND_DRAG': 'SHORTCUTS_DIALOG.MANUAL_NOTES_SELECTION',
  }
};

export default SHORTCUTS;